User can see prompt for current letter.
ChrisJVoss/typing-test pull request #4
Opened 2017-06-09 21:29 UTC by ChrisJVoss

![screen shot 2017-06-09 at 2 25 59 pm](https://user-images.githubusercontent.com/29046393/26995181-0e0cb732-4d20-11e7-8aeb-3f0e307487a3.png)

2017-06-09 22:03 UTC, victormejia requested changes
While this works, you want to do this initial highlight of the first letter in JavaScript. To do so, you will probably need to render the text as `spans`s

2017-06-12 17:39 UTC, thebearingedge requested changes
Please re-title the Pull Request to explain the user value. It's generally acceptable to just re-use the Issue title.

2017-06-12 18:10 UTC, victormejia requested changes

2017-06-12 18:10 UTC, victormejia commented on main.js
> +  $text.className = ('id')
a class name of `id` is a bit awkward. Perhaps give a class name of `character`

2017-06-12 18:16 UTC, victormejia commented on main.js
> +  $text.className = ('character')
no need to set this to `('character')`, just `'character'`

2017-06-12 18:18 UTC, victormejia approved these changes

2017-06-12 18:19 UTC, merged